### ISSUE TITLE
Unix sockets for postgres

### ISSUE THREAD

**Issue by louisroyer** [nextmn/testbed#54]
- modify `psqlconn` in nextmn/srv6 to check for `POSTGRES_UNIX_SOCKET_PATH` => `postgres:///dbname?host=/var/run/postgresql/`
- a volume for each db

```
services:
  r0:
    environment:
      POSTGRES_UNIX_SOCKET_PATH:/var/run/postgresql/
    volumes:
      - r0-db-socket:/var/run/postgresql
  r0-db:
    volumes:
      - r0-db-socket:/var/run/postgresql
volumes:
  r0-db-socket
```
